# Generated by Django 5.2.5 on 2025-08-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_brand_alter_category_image_product_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/'),
        ),
    ]
