# Generated by Django 5.2.5 on 2025-08-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_sku_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtext', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
