# Generated by Django 5.2.5 on 2025-08-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='heros/'),
        ),
    ]
