# Generated by Django 5.2.5 on 2025-09-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='gallery_image',
            new_name='image',
        ),
    ]
