# Generated by Django 5.2.5 on 2025-09-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
