# Generated by Django 5.2.5 on 2025-09-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_orderitem_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
