# Generated by Django 5.2.5 on 2025-09-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='api_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
