# Generated by Django 5.2.5 on 2025-09-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_appuser_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_items/'),
        ),
    ]
