# Generated by Django 5.2.5 on 2025-09-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('process', 'In Process'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('on_the_way', 'On The Way')], default='pending', max_length=20),
        ),
    ]
