# Generated by Django 5.2.5 on 2025-10-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_appuser_image_appuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal Order'), ('redeem', 'Redeem Order')], default='normal', max_length=20),
        ),
    ]
