# Generated by Django 5.2.5 on 2025-10-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('order', 'Normal Order'), ('redeem', 'Redeem Order')], default='normal', max_length=20),
        ),
    ]
