# Generated by Django 5.2.5 on 2025-10-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_appuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/'),
        ),
    ]
