# Generated by Django 5.2.5 on 2025-10-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_product_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery_image',
        ),
    ]
