# Generated by Django 5.2.5 on 2025-10-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='apply_all_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='apply_all_users',
            field=models.BooleanField(default=False),
        ),
    ]
