# Generated by Django 5.2.5 on 2025-10-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_discount_apply_all_products_discount_apply_all_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_image',
        ),
    ]
