# Generated by Django 5.2.5 on 2025-10-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_image_product_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='image',
        ),
    ]
