# Generated by Django 5.2.5 on 2026-04-20 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media_library/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('folder', models.CharField(choices=[('general', 'General'), ('products', 'Products'), ('banners', 'Banners'), ('brands', 'Brands'), ('category', 'Category'), ('users', 'Users'), ('ads', 'Ads'), ('heros', 'Heroes'), ('redeem', 'Redeem')], default='general', max_length=50)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='bytes')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
